name = raw_input("Enter your name: ")
	num = raw_input("How many pizzas? ")
	pep = raw_input("How many pepperonis? ")
	olv = raw_input("How many olives? ")
	print(name + " ordered " + num + " pizzas with " + pep + "pepperonis and " + olv + " olives.")