name=raw_input("What is your name?")
x=raw_input("How many pizzas would you like?")
y=raw_input("How many peppornis would you like?")
z=raw_input("How many olives would you like?")
print("name ordered x pizzas with y peppornis and z olives")