name = raw_input("What is your name? ")
pizzas = raw_input("How many pizzas do you want? ")
olives = raw_input("How many olives do you want? ")
pepperoni = raw_input("How many pepperonis do you want? ")
print (name + " ordered " + str(pizzas) + " pizzas with " + str(pepperoni) + " pepperonis and " + str(olives) +  " olives.")
